### ISSUE TITLE
Problems with the example

### ISSUE THREAD

**Issue by ceicke** [remiprev/her#50]
Hi,

I am trying to use the 'her' gem as it seems like a really good gem. However I can't even get the simplest thing to work. Here is the error I am getting

``` ruby
1.9.2p320 :001 > s = Fileflow::Student.find(1)
URI::InvalidURIError: query conflicts with opaque
    from /Users/ceicke/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/uri/generic.rb:521:in `check_query'
    from /Users/ceicke/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/uri/generic.rb:540:in `query='
    from /Users/ceicke/.rvm/gems/ruby-1.9.2-p320@intranet/gems/faraday-0.8.4/lib/faraday/connection.rb:277:in `build_exclusive_url'
    from /Users/ceicke/.rvm/gems/ruby-1.9.2-p320@intranet/gems/faraday-0.8.4/lib/faraday/request.rb:94:in `to_env'
    from /Users/ceicke/.rvm/gems/ruby-1.9.2-p320@intranet/gems/faraday-0.8.4/lib/faraday/connection.rb:225:in `run_request'
    from /Users/ceicke/.rvm/gems/ruby-1.9.2-p320@intranet/gems/faraday-0.8.4/lib/faraday/connection.rb:87:in `get'
    from /Users/ceicke/.rvm/gems/ruby-1.9.2-p320@intranet/gems/her-0.2/lib/her/api.rb:67:in `request'
    from /Users/ceicke/.rvm/gems/ruby-1.9.2-p320@intranet/gems/her-0.2/lib/her/model/http.rb:37:in `request'
    from /Users/ceicke/.rvm/gems/ruby-1.9.2-p320@intranet/gems/her-0.2/lib/her/model/orm.rb:53:in `find'
    from (irb):1
    from /Users/ceicke/.rvm/gems/ruby-1.9.2-p320@intranet/gems/railties-3.0.10/lib/rails/commands/console.rb:44:in `start'
    from /Users/ceicke/.rvm/gems/ruby-1.9.2-p320@intranet/gems/railties-3.0.10/lib/rails/commands/console.rb:8:in `start'
    from /Users/ceicke/.rvm/gems/ruby-1.9.2-p320@intranet/gems/railties-3.0.10/lib/rails/commands.rb:23:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

My setup is pretty default:

``` ruby
# config/initializers/her.rb
Her::API.setup :url => "http://127.0.0.1:3003/api/v1/" do |connection|
  connection.use Faraday::BasicAuthentication.basic_auth("user","pass")
  connection.use Faraday::Request::UrlEncoded
  connection.use Her::Middleware::DefaultParseJSON
  connection.use Faraday::Adapter::NetHttp
end
```

``` ruby
module Fileflow
  class Student
        include Her::Model
  end
end
```

I'm suspecting that the URL is not correctly built, but I have no idea where to hook into...

Any help would be appreciated,
Christoph

**Comment by nickweavers** [comment]
I am not able to get basic authentication working,. Here's what I have tried:

Her::API.setup :url => "https://my.favourite_api.org" do |connection|

  # Authentication
  connection.use Faraday::Request::BasicAuthentication "itsme", "letmein"

The RubyMine debugger tells me:

Uncaught exception: undefined method `BasicAuthentication' for Faraday::Request:Class

Can anyone help?

**Comment by nickweavers** [comment]
It was simply a missing comma:
connection.use Faraday::Request::BasicAuthentication, "itsme", "letmein"

**Comment by jhirbour** [comment]
@nickweavers comment works for me. I added a PR to the readme.
